### ISSUE TITLE
[1.12.2] Crashes before after I get past the Loading screen

### ISSUE THREAD

**Issue by Gh0ost85** [Bluexin/mcui#18]
This is the Crash Report.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  wings (Wings-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 12/11/19 5:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Sword Art Online UI (saoui)
Caused by: java.lang.NullPointerException
	at net.minecraft.client.gui.FontRenderer.bindTexture(FontRenderer.java:875)
	at net.minecraft.client.gui.FontRenderer.<init>(FontRenderer.java:60)
	at com.saomc.saoui.GLCore.setFont(GLCore.kt:90)
	at com.saomc.saoui.config.OptionCore.flip(OptionCore.kt:126)
	at com.saomc.saoui.config.OptionCore.enable(OptionCore.kt:175)
	at com.saomc.saoui.config.ConfigHandler$preInit$2$2.accept(ConfigHandler.kt:56)
	at com.saomc.saoui.config.ConfigHandler$preInit$2$2.accept(ConfigHandler.kt:32)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.saomc.saoui.config.ConfigHandler.preInit(ConfigHandler.kt:54)
	at com.saomc.saoui.SAOCore.preInit(SAOCore.kt:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 354325768 bytes (337 MB) / 771751936 bytes (736 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 24 mods loaded, 23 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version       | Source                                 | Signature                                |
	|:----- |:------------------ |:------------- |:-------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft          | 1.12.2        | minecraft.jar                          | None                                     |
	| LCH   | mcp                | 9.42          | minecraft.jar                          | None                                     |
	| LCH   | FML                | 8.0.99.99     | forge-1.12.2-14.23.5.2838.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge              | 14.23.5.2838  | forge-1.12.2-14.23.5.2838.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | bspkrscore         | 7.6.0.1       | [1.12]bspkrsCore-universal-7.6.0.1.jar | None                                     |
	| LCH   | treecapitator      | 1.43.0        | [1.12]TreeCapitator-client-1.43.0.jar  | None                                     |
	| LCH   | applecore          | 3.2.0         | AppleCore-mc1.12.2-3.2.0.jar           | None                                     |
	| LCH   | armourers_workshop | 1.12.2-0.49.1 | Armourers-Workshop-1.12.2-0.49.1.jar   | None                                     |
	| LCH   | baubles            | 1.5.2         | Baubles-Mod-1.12.2.jar                 | None                                     |
	| LCH   | bettercombatmod    | 1.5.6         | BetterCombat-1.12.2-1.5.6 (1).jar      | None                                     |
	| LCH   | forgelin           | 1.8.4         | Forgelin-1.8.4.jar                     | None                                     |
	| LCH   | cfm                | 6.3.1         | furniture-6.3.1-1.12.2.jar             | None                                     |
	| LCH   | hungerinpeace      | 1.0.0         | HungerInPeace-mc1.12-1.0.0 (1).jar     | None                                     |
	| LCH   | jei                | 4.15.0.268    | jei_1.12.2-4.15.0.268.jar              | None                                     |
	| LCH   | librarianlib       | 4.20          | librarianlib-1.12.2-4.20-release.jar   | None                                     |
	| LCH   | mca                | 6.0.1         | MCA-1.12.2-6.0.1-universal.jar         | None                                     |
	| LCH   | moreswordonline    | 2.8.2         | MoreSwordOnline-Mod-1.12.2 (1).jar     | None                                     |
	| LCH   | saomclib           | 1.4.2         | saomc-lib-1.12.2-1.4.2.jar             | None                                     |
	| LCE   | saoui              | 2.0.8         | saoui-1.12.2-2.0.8.jar                 | None                                     |
	| LC    | llibrary           | 1.7.19        | llibrary-1.7.19-1.12.2 (1).jar         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LC    | wings              | 1.1.4         | Wings-Mod-1.12.2.jar                   | None                                     |
	| LC    | bauble_wings       | 1.0.0         | Wings-Mod-1.12.2.jar                   | None                                     |
	| LC    | librarianliblate   | 4.20          | librarianlib-1.12.2-4.20-release.jar   | None                                     |
	| UD    | mobends_wings      | 1.0.0         | Wings-Mod-1.12.2.jar                   | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
LibrarianLib Plugin (librarianlib-1.12.2-4.20-release.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
ForgelinPlugin (Forgelin-1.8.4.jar)
  
wings (Wings-Mod-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4358' Renderer: 'Intel(R) HD Graphics'

**Comment by Tencao** [comment]
Fixed in next version

**Comment by Gh0ost85** [comment]
May I know when it will be out, I really want to make a Modpack and server so me and my Mates can Pretty much play SAO.

**Comment by Tencao** [comment]
Very soon, it should have been out yesterday but some last minute bugs has caused me to delay the update to make sure they're fixed. This next build should be the most stable version for a while so outside any last minute updates, you should probably base your modpack around that version for awhile.

**Comment by Gh0ost85** [comment]
Sorry to bother, But it been a couple days sooo, do you have a date it will be updated?

**Comment by Tencao** [comment]
Appologies, but been busy with christmas coming up, bugs are been worked on but I don't want to release something with known bugs still present.

**Comment by Tencao** [comment]
Fixed in 2.0.9
